// This file automatically generated by gen_kernel_syscalls_translation.py
// DO NOT EDIT!

long RunGuestSyscallImpl(long guest_nr,
                         long arg_1,
                         long arg_2,
                         long arg_3,
                         long arg_4,
                         long arg_5,
                         long arg_6) {
  switch (guest_nr) {
    case 0x0f'0002:  // __ARM_NR_cacheflush
      // missing on x86
      return RunGuestSyscall___ARM_NR_cacheflush(arg_1, arg_2, arg_3);
    case 0x0f'0005:  // __ARM_NR_set_tls
      // missing on x86
      return RunGuestSyscall___ARM_NR_set_tls(arg_1);
    case 140:  // __NR__llseek
      return syscall(140, arg_1, arg_2, arg_3, arg_4, arg_5);
    case 142:  // __NR__newselect
      return syscall(142, arg_1, arg_2, arg_3, arg_4, arg_5);
    case 149:  // __NR__sysctl
      return syscall(149, arg_1);
    case 285:  // __NR_accept
      // socketcall
      return RunGuestSyscall___NR_accept(arg_1, arg_2, arg_3);
    case 366:  // __NR_accept4
      // socketcall
      return RunGuestSyscall___NR_accept4(arg_1, arg_2, arg_3, arg_4);
    case 33:  // __NR_access
      return syscall(33, arg_1, arg_2);
    case 51:  // __NR_acct
      return syscall(51, arg_1);
    case 309:  // __NR_add_key
      return syscall(286, arg_1, arg_2, arg_3, arg_4, arg_5);
    case 124:  // __NR_adjtimex
      return syscall(124, arg_1);
    case 270:  // __NR_arm_fadvise64_64
      // missing on x86
      return RunGuestSyscall___NR_arm_fadvise64_64(arg_1, arg_2, arg_3, arg_4, arg_5, arg_6);
    case 341:  // __NR_arm_sync_file_range
      // missing on x86
      return RunGuestSyscall___NR_arm_sync_file_range(arg_1, arg_2, arg_3, arg_4, arg_5, arg_6);
    case 134:  // __NR_bdflush
      return syscall(134, arg_1, arg_2);
    case 282:  // __NR_bind
      // socketcall
      return RunGuestSyscall___NR_bind(arg_1, arg_2, arg_3);
    case 386:  // __NR_bpf
      // incompatible prototype
      return RunGuestSyscall___NR_bpf(arg_1, arg_2, arg_3);
    case 45:  // __NR_brk
      return syscall(45, arg_1);
    case 184:  // __NR_capget
      return syscall(184, arg_1, arg_2);
    case 185:  // __NR_capset
      return syscall(185, arg_1, arg_2);
    case 12:  // __NR_chdir
      return syscall(12, arg_1);
    case 15:  // __NR_chmod
      return syscall(15, arg_1, arg_2);
    case 182:  // __NR_chown
      return syscall(182, arg_1, arg_2, arg_3);
    case 212:  // __NR_chown32
      return syscall(212, arg_1, arg_2, arg_3);
    case 61:  // __NR_chroot
      return syscall(61, arg_1);
    case 372:  // __NR_clock_adjtime
      return syscall(343, arg_1, arg_2);
    case 405:  // __NR_clock_adjtime64
      return syscall(405, arg_1, arg_2);
    case 264:  // __NR_clock_getres
      return syscall(266, arg_1, arg_2);
    case 406:  // __NR_clock_getres_time64
      return syscall(406, arg_1, arg_2);
    case 263:  // __NR_clock_gettime
      return syscall(265, arg_1, arg_2);
    case 403:  // __NR_clock_gettime64
      return syscall(403, arg_1, arg_2);
    case 265:  // __NR_clock_nanosleep
      return syscall(267, arg_1, arg_2, arg_3, arg_4);
    case 407:  // __NR_clock_nanosleep_time64
      return syscall(407, arg_1, arg_2, arg_3, arg_4);
    case 262:  // __NR_clock_settime
      return syscall(264, arg_1, arg_2);
    case 404:  // __NR_clock_settime64
      return syscall(404, arg_1, arg_2);
    case 120:  // __NR_clone
      // custom syscall
      return RunGuestSyscall___NR_clone(arg_1, arg_2, arg_3, arg_4, arg_5);
    case 435:  // __NR_clone3
      // custom syscall
      return RunGuestSyscall___NR_clone3(arg_1, arg_2);
    case 6:  // __NR_close
      // /proc/self/maps emulation
      return RunGuestSyscall___NR_close(arg_1);
    case 283:  // __NR_connect
      // socketcall
      return RunGuestSyscall___NR_connect(arg_1, arg_2, arg_3);
    case 391:  // __NR_copy_file_range
      return syscall(377, arg_1, arg_2, arg_3, arg_4, arg_5, arg_6);
    case 8:  // __NR_creat
      return syscall(8, arg_1, arg_2);
    case 129:  // __NR_delete_module
      return syscall(129, arg_1, arg_2);
    case 41:  // __NR_dup
      return syscall(41, arg_1);
    case 63:  // __NR_dup2
      return syscall(63, arg_1, arg_2);
    case 358:  // __NR_dup3
      return syscall(330, arg_1, arg_2, arg_3);
    case 250:  // __NR_epoll_create
      return syscall(254, arg_1);
    case 357:  // __NR_epoll_create1
      return syscall(329, arg_1);
    case 251:  // __NR_epoll_ctl
      // incompatible prototype
      return RunGuestSyscall___NR_epoll_ctl(arg_1, arg_2, arg_3, arg_4);
    case 346:  // __NR_epoll_pwait
      // incompatible prototype
      return RunGuestSyscall___NR_epoll_pwait(arg_1, arg_2, arg_3, arg_4, arg_5, arg_6);
    case 252:  // __NR_epoll_wait
      // incompatible prototype
      return RunGuestSyscall___NR_epoll_wait(arg_1, arg_2, arg_3, arg_4);
    case 351:  // __NR_eventfd
      return syscall(323, arg_1);
    case 356:  // __NR_eventfd2
      return syscall(328, arg_1, arg_2);
    case 11:  // __NR_execve
      // custom syscall
      return RunGuestSyscall___NR_execve(arg_1, arg_2, arg_3);
    case 387:  // __NR_execveat
      // custom syscall
      return RunGuestSyscall___NR_execveat(arg_1, arg_2, arg_3, arg_4, arg_5);
    case 1:  // __NR_exit
      // cleans guest thread
      return RunGuestSyscall___NR_exit(arg_1);
    case 248:  // __NR_exit_group
      return syscall(252, arg_1);
    case 334:  // __NR_faccessat
      // follows symlinks
      return RunGuestSyscall___NR_faccessat(arg_1, arg_2, arg_3);
    case 352:  // __NR_fallocate
      return syscall(324, arg_1, arg_2, arg_3, arg_4, arg_5, arg_6);
    case 367:  // __NR_fanotify_init
      return syscall(338, arg_1, arg_2);
    case 368:  // __NR_fanotify_mark
      return syscall(339, arg_1, arg_2, arg_3, arg_4, arg_5, arg_6);
    case 133:  // __NR_fchdir
      return syscall(133, arg_1);
    case 94:  // __NR_fchmod
      return syscall(94, arg_1, arg_2);
    case 333:  // __NR_fchmodat
      return syscall(306, arg_1, arg_2, arg_3);
    case 95:  // __NR_fchown
      return syscall(95, arg_1, arg_2, arg_3);
    case 207:  // __NR_fchown32
      return syscall(207, arg_1, arg_2, arg_3);
    case 325:  // __NR_fchownat
      return syscall(298, arg_1, arg_2, arg_3, arg_4, arg_5);
    case 55:  // __NR_fcntl
      // custom syscall
      return RunGuestSyscall___NR_fcntl(arg_1, arg_2, arg_3);
    case 221:  // __NR_fcntl64
      // custom syscall
      return RunGuestSyscall___NR_fcntl64(arg_1, arg_2, arg_3);
    case 148:  // __NR_fdatasync
      return syscall(148, arg_1);
    case 231:  // __NR_fgetxattr
      return syscall(231, arg_1, arg_2, arg_3, arg_4);
    case 379:  // __NR_finit_module
      return syscall(350, arg_1, arg_2, arg_3);
    case 234:  // __NR_flistxattr
      return syscall(234, arg_1, arg_2, arg_3);
    case 143:  // __NR_flock
      return syscall(143, arg_1, arg_2);
    case 2:  // __NR_fork
      // custom syscall
      return RunGuestSyscall___NR_fork();
    case 237:  // __NR_fremovexattr
      return syscall(237, arg_1, arg_2);
    case 431:  // __NR_fsconfig
      return syscall(431, arg_1, arg_2, arg_3, arg_4, arg_5);
    case 228:  // __NR_fsetxattr
      return syscall(228, arg_1, arg_2, arg_3, arg_4, arg_5);
    case 432:  // __NR_fsmount
      return syscall(432, arg_1, arg_2, arg_3);
    case 430:  // __NR_fsopen
      return syscall(430, arg_1, arg_2);
    case 433:  // __NR_fspick
      return syscall(433, arg_1, arg_2, arg_3);
    case 108:  // __NR_fstat
      // /proc/self/maps emulation
      return RunGuestSyscall___NR_fstat(arg_1, arg_2);
    case 197:  // __NR_fstat64
      // incompatible prototype
      return RunGuestSyscall___NR_fstat64(arg_1, arg_2);
    case 327:  // __NR_fstatat64
      // incompatible prototype
      return RunGuestSyscall___NR_fstatat64(arg_1, arg_2, arg_3, arg_4);
    case 100:  // __NR_fstatfs
      // /proc/self/maps emulation
      return RunGuestSyscall___NR_fstatfs(arg_1, arg_2);
    case 267:  // __NR_fstatfs64
      // statfs64 size mismatch
      return RunGuestSyscall___NR_fstatfs64(arg_1, arg_2, arg_3);
    case 118:  // __NR_fsync
      return syscall(118, arg_1);
    case 93:  // __NR_ftruncate
      return syscall(93, arg_1, arg_2);
    case 194:  // __NR_ftruncate64
      return syscall(194, arg_1, arg_3, arg_4);
    case 240:  // __NR_futex
      return syscall(240, arg_1, arg_2, arg_3, arg_4, arg_5, arg_6);
    case 422:  // __NR_futex_time64
      return syscall(422, arg_1, arg_2, arg_3, arg_4, arg_5, arg_6);
    case 326:  // __NR_futimesat
      return syscall(299, arg_1, arg_2, arg_3);
    case 320:  // __NR_get_mempolicy
      // missing prototype
      TRACE("unsupported syscall __NR_get_mempolicy");
      errno = ENOSYS;
      return -1;
    case 339:  // __NR_get_robust_list
      return syscall(312, arg_1, arg_2, arg_3);
    case 345:  // __NR_getcpu
      return syscall(318, arg_1, arg_2, arg_3);
    case 183:  // __NR_getcwd
      return syscall(183, arg_1, arg_2);
    case 141:  // __NR_getdents
      return syscall(141, arg_1, arg_2, arg_3);
    case 217:  // __NR_getdents64
      // incompatible prototype
      return RunGuestSyscall___NR_getdents64(arg_1, arg_2, arg_3);
    case 50:  // __NR_getegid
      return syscall(50);
    case 202:  // __NR_getegid32
      return syscall(202);
    case 49:  // __NR_geteuid
      return syscall(49);
    case 201:  // __NR_geteuid32
      return syscall(201);
    case 47:  // __NR_getgid
      return syscall(47);
    case 200:  // __NR_getgid32
      return syscall(200);
    case 80:  // __NR_getgroups
      return syscall(80, arg_1, arg_2);
    case 205:  // __NR_getgroups32
      return syscall(205, arg_1, arg_2);
    case 105:  // __NR_getitimer
      return syscall(105, arg_1, arg_2);
    case 287:  // __NR_getpeername
      // socketcall
      return RunGuestSyscall___NR_getpeername(arg_1, arg_2, arg_3);
    case 132:  // __NR_getpgid
      return syscall(132, arg_1);
    case 65:  // __NR_getpgrp
      return syscall(65);
    case 20:  // __NR_getpid
      return syscall(20);
    case 64:  // __NR_getppid
      return syscall(64);
    case 96:  // __NR_getpriority
      return syscall(96, arg_1, arg_2);
    case 384:  // __NR_getrandom
      return syscall(355, arg_1, arg_2, arg_3);
    case 171:  // __NR_getresgid
      return syscall(171, arg_1, arg_2, arg_3);
    case 211:  // __NR_getresgid32
      return syscall(211, arg_1, arg_2, arg_3);
    case 165:  // __NR_getresuid
      return syscall(165, arg_1, arg_2, arg_3);
    case 209:  // __NR_getresuid32
      return syscall(209, arg_1, arg_2, arg_3);
    case 77:  // __NR_getrusage
      return syscall(77, arg_1, arg_2);
    case 147:  // __NR_getsid
      return syscall(147, arg_1);
    case 286:  // __NR_getsockname
      // socketcall
      return RunGuestSyscall___NR_getsockname(arg_1, arg_2, arg_3);
    case 295:  // __NR_getsockopt
      // socketcall
      return RunGuestSyscall___NR_getsockopt(arg_1, arg_2, arg_3, arg_4, arg_5);
    case 224:  // __NR_gettid
      return syscall(224);
    case 78:  // __NR_gettimeofday
      return syscall(78, arg_1, arg_2);
    case 24:  // __NR_getuid
      return syscall(24);
    case 199:  // __NR_getuid32
      return syscall(199);
    case 229:  // __NR_getxattr
      return syscall(229, arg_1, arg_2, arg_3, arg_4);
    case 128:  // __NR_init_module
      return syscall(128, arg_1, arg_2, arg_3);
    case 317:  // __NR_inotify_add_watch
      return syscall(292, arg_1, arg_2, arg_3);
    case 316:  // __NR_inotify_init
      return syscall(291);
    case 360:  // __NR_inotify_init1
      return syscall(332, arg_1);
    case 318:  // __NR_inotify_rm_watch
      return syscall(293, arg_1, arg_2);
    case 247:  // __NR_io_cancel
      return syscall(249, arg_1, arg_2, arg_3);
    case 244:  // __NR_io_destroy
      return syscall(246, arg_1);
    case 245:  // __NR_io_getevents
      return syscall(247, arg_1, arg_2, arg_3, arg_4, arg_5);
    case 399:  // __NR_io_pgetevents
      return syscall(385, arg_1, arg_2, arg_3, arg_4, arg_5, arg_6);
    case 416:  // __NR_io_pgetevents_time64
      return syscall(416, arg_1, arg_2, arg_3, arg_4, arg_5, arg_6);
    case 243:  // __NR_io_setup
      return syscall(245, arg_1, arg_2);
    case 246:  // __NR_io_submit
      return syscall(248, arg_1, arg_2, arg_3);
    case 426:  // __NR_io_uring_enter
      return syscall(426, arg_1, arg_2, arg_3, arg_4, arg_5, arg_6);
    case 427:  // __NR_io_uring_register
      return syscall(427, arg_1, arg_2, arg_3, arg_4);
    case 425:  // __NR_io_uring_setup
      return syscall(425, arg_1, arg_2);
    case 54:  // __NR_ioctl
      // custom syscall
      return RunGuestSyscall___NR_ioctl(arg_1, arg_2, arg_3);
    case 315:  // __NR_ioprio_get
      return syscall(290, arg_1, arg_2);
    case 314:  // __NR_ioprio_set
      return syscall(289, arg_1, arg_2, arg_3);
    case 378:  // __NR_kcmp
      return syscall(349, arg_1, arg_2, arg_3, arg_4, arg_5);
    case 401:  // __NR_kexec_file_load
      // missing prototype
      TRACE("unsupported syscall __NR_kexec_file_load");
      errno = ENOSYS;
      return -1;
    case 347:  // __NR_kexec_load
      return syscall(283, arg_1, arg_2, arg_3, arg_4);
    case 311:  // __NR_keyctl
      return syscall(288, arg_1, arg_2, arg_3, arg_4, arg_5);
    case 37:  // __NR_kill
      return syscall(37, arg_1, arg_2);
    case 16:  // __NR_lchown
      return syscall(16, arg_1, arg_2, arg_3);
    case 198:  // __NR_lchown32
      return syscall(198, arg_1, arg_2, arg_3);
    case 230:  // __NR_lgetxattr
      return syscall(230, arg_1, arg_2, arg_3, arg_4);
    case 9:  // __NR_link
      return syscall(9, arg_1, arg_2);
    case 330:  // __NR_linkat
      return syscall(303, arg_1, arg_2, arg_3, arg_4, arg_5);
    case 284:  // __NR_listen
      // socketcall
      return RunGuestSyscall___NR_listen(arg_1, arg_2);
    case 232:  // __NR_listxattr
      return syscall(232, arg_1, arg_2, arg_3);
    case 233:  // __NR_llistxattr
      return syscall(233, arg_1, arg_2, arg_3);
    case 249:  // __NR_lookup_dcookie
      return syscall(253, arg_1, arg_2, arg_3, arg_4);
    case 236:  // __NR_lremovexattr
      return syscall(236, arg_1, arg_2);
    case 19:  // __NR_lseek
      return syscall(19, arg_1, arg_2, arg_3);
    case 227:  // __NR_lsetxattr
      return syscall(227, arg_1, arg_2, arg_3, arg_4, arg_5);
    case 107:  // __NR_lstat
      return syscall(107, arg_1, arg_2);
    case 196:  // __NR_lstat64
      // incompatible prototype
      return RunGuestSyscall___NR_lstat64(arg_1, arg_2);
    case 220:  // __NR_madvise
      return syscall(219, arg_1, arg_2, arg_3);
    case 319:  // __NR_mbind
      // missing prototype
      TRACE("unsupported syscall __NR_mbind");
      errno = ENOSYS;
      return -1;
    case 389:  // __NR_membarrier
      return syscall(375, arg_1, arg_2);
    case 385:  // __NR_memfd_create
      return syscall(356, arg_1, arg_2);
    case 400:  // __NR_migrate_pages
      // missing prototype
      TRACE("unsupported syscall __NR_migrate_pages");
      errno = ENOSYS;
      return -1;
    case 219:  // __NR_mincore
      return syscall(218, arg_1, arg_2, arg_3);
    case 39:  // __NR_mkdir
      return syscall(39, arg_1, arg_2);
    case 323:  // __NR_mkdirat
      return syscall(296, arg_1, arg_2, arg_3);
    case 14:  // __NR_mknod
      return syscall(14, arg_1, arg_2, arg_3);
    case 324:  // __NR_mknodat
      return syscall(297, arg_1, arg_2, arg_3, arg_4);
    case 150:  // __NR_mlock
      return syscall(150, arg_1, arg_2);
    case 390:  // __NR_mlock2
      return syscall(376, arg_1, arg_2, arg_3);
    case 152:  // __NR_mlockall
      return syscall(152, arg_1);
    case 192:  // __NR_mmap2
      // changes memory protection
      return RunGuestSyscall___NR_mmap2(arg_1, arg_2, arg_3, arg_4, arg_5, arg_6);
    case 21:  // __NR_mount
      return syscall(21, arg_1, arg_2, arg_3, arg_4, arg_5);
    case 429:  // __NR_move_mount
      return syscall(429, arg_1, arg_2, arg_3, arg_4, arg_5);
    case 344:  // __NR_move_pages
      // missing prototype
      TRACE("unsupported syscall __NR_move_pages");
      errno = ENOSYS;
      return -1;
    case 125:  // __NR_mprotect
      // changes memory protection
      return RunGuestSyscall___NR_mprotect(arg_1, arg_2, arg_3);
    case 279:  // __NR_mq_getsetattr
      return syscall(282, arg_1, arg_2, arg_3);
    case 278:  // __NR_mq_notify
      // incompatible prototype
      return RunGuestSyscall___NR_mq_notify(arg_1, arg_2);
    case 274:  // __NR_mq_open
      return syscall(277, arg_1, arg_2, arg_3, arg_4);
    case 277:  // __NR_mq_timedreceive
      return syscall(280, arg_1, arg_2, arg_3, arg_4, arg_5);
    case 419:  // __NR_mq_timedreceive_time64
      return syscall(419, arg_1, arg_2, arg_3, arg_4, arg_5);
    case 276:  // __NR_mq_timedsend
      return syscall(279, arg_1, arg_2, arg_3, arg_4, arg_5);
    case 418:  // __NR_mq_timedsend_time64
      return syscall(418, arg_1, arg_2, arg_3, arg_4, arg_5);
    case 275:  // __NR_mq_unlink
      return syscall(278, arg_1);
    case 163:  // __NR_mremap
      // changes memory protection
      return RunGuestSyscall___NR_mremap(arg_1, arg_2, arg_3, arg_4, arg_5);
    case 304:  // __NR_msgctl
      // sys_old_msgctl on arm but sys_msgctl on x86
      return RunGuestSyscall___NR_msgctl(arg_1, arg_2, arg_3);
    case 303:  // __NR_msgget
      return syscall(399, arg_1, arg_2);
    case 302:  // __NR_msgrcv
      return syscall(401, arg_1, arg_2, arg_3, arg_4, arg_5);
    case 301:  // __NR_msgsnd
      return syscall(400, arg_1, arg_2, arg_3, arg_4);
    case 144:  // __NR_msync
      return syscall(144, arg_1, arg_2, arg_3);
    case 151:  // __NR_munlock
      return syscall(151, arg_1, arg_2);
    case 153:  // __NR_munlockall
      return syscall(153);
    case 91:  // __NR_munmap
      // changes memory protection
      return RunGuestSyscall___NR_munmap(arg_1, arg_2);
    case 370:  // __NR_name_to_handle_at
      return syscall(341, arg_1, arg_2, arg_3, arg_4, arg_5);
    case 162:  // __NR_nanosleep
      return syscall(162, arg_1, arg_2);
    case 169:  // __NR_nfsservctl
      return syscall(169);
    case 34:  // __NR_nice
      return syscall(34, arg_1);
    case 5:  // __NR_open
      // follows symlinks, open flags value mismatch
      return RunGuestSyscall___NR_open(arg_1, arg_2, arg_3);
    case 371:  // __NR_open_by_handle_at
      return syscall(342, arg_1, arg_2, arg_3);
    case 428:  // __NR_open_tree
      return syscall(428, arg_1, arg_2, arg_3);
    case 322:  // __NR_openat
      // follows symlinks, open flags value mismatch
      return RunGuestSyscall___NR_openat(arg_1, arg_2, arg_3, arg_4);
    case 29:  // __NR_pause
      return syscall(29);
    case 271:  // __NR_pciconfig_iobase
      // missing prototype
      TRACE("unsupported syscall __NR_pciconfig_iobase");
      errno = ENOSYS;
      return -1;
    case 272:  // __NR_pciconfig_read
      // missing on x86
      return RunGuestSyscall___NR_pciconfig_read(arg_1, arg_2, arg_3, arg_4, arg_5);
    case 273:  // __NR_pciconfig_write
      // missing on x86
      return RunGuestSyscall___NR_pciconfig_write(arg_1, arg_2, arg_3, arg_4, arg_5);
    case 364:  // __NR_perf_event_open
      return syscall(336, arg_1, arg_2, arg_3, arg_4, arg_5);
    case 136:  // __NR_personality
      return syscall(136, arg_1);
    case 434:  // __NR_pidfd_open
      return syscall(434, arg_1, arg_2);
    case 424:  // __NR_pidfd_send_signal
      return syscall(424, arg_1, arg_2, arg_3, arg_4);
    case 42:  // __NR_pipe
      return syscall(42, arg_1);
    case 359:  // __NR_pipe2
      return syscall(331, arg_1, arg_2);
    case 218:  // __NR_pivot_root
      return syscall(217, arg_1, arg_2);
    case 395:  // __NR_pkey_alloc
      // missing prototype
      TRACE("unsupported syscall __NR_pkey_alloc");
      errno = ENOSYS;
      return -1;
    case 396:  // __NR_pkey_free
      // missing prototype
      TRACE("unsupported syscall __NR_pkey_free");
      errno = ENOSYS;
      return -1;
    case 394:  // __NR_pkey_mprotect
      // missing prototype
      TRACE("unsupported syscall __NR_pkey_mprotect");
      errno = ENOSYS;
      return -1;
    case 168:  // __NR_poll
      return syscall(168, arg_1, arg_2, arg_3);
    case 336:  // __NR_ppoll
      return syscall(309, arg_1, arg_2, arg_3, arg_4, arg_5);
    case 414:  // __NR_ppoll_time64
      return syscall(414, arg_1, arg_2, arg_3, arg_4, arg_5);
    case 172:  // __NR_prctl
      // custom syscall
      return RunGuestSyscall___NR_prctl(arg_1, arg_2, arg_3, arg_4, arg_5);
    case 180:  // __NR_pread64
      return syscall(180, arg_1, arg_2, arg_3, arg_5, arg_6);
    case 361:  // __NR_preadv
      return syscall(333, arg_1, arg_2, arg_3, arg_4, arg_5);
    case 392:  // __NR_preadv2
      return syscall(378, arg_1, arg_2, arg_3, arg_4, arg_5, arg_6);
    case 369:  // __NR_prlimit64
      return syscall(340, arg_1, arg_2, arg_3, arg_4);
    case 376:  // __NR_process_vm_readv
      return syscall(347, arg_1, arg_2, arg_3, arg_4, arg_5, arg_6);
    case 377:  // __NR_process_vm_writev
      return syscall(348, arg_1, arg_2, arg_3, arg_4, arg_5, arg_6);
    case 335:  // __NR_pselect6
      return syscall(308, arg_1, arg_2, arg_3, arg_4, arg_5, arg_6);
    case 413:  // __NR_pselect6_time64
      return syscall(413, arg_1, arg_2, arg_3, arg_4, arg_5, arg_6);
    case 26:  // __NR_ptrace
      // custom syscall
      return RunGuestSyscall___NR_ptrace(arg_1, arg_2, arg_3, arg_4);
    case 181:  // __NR_pwrite64
      return syscall(181, arg_1, arg_2, arg_3, arg_5, arg_6);
    case 362:  // __NR_pwritev
      return syscall(334, arg_1, arg_2, arg_3, arg_4, arg_5);
    case 393:  // __NR_pwritev2
      return syscall(379, arg_1, arg_2, arg_3, arg_4, arg_5, arg_6);
    case 131:  // __NR_quotactl
      return syscall(131, arg_1, arg_2, arg_3, arg_4);
    case 3:  // __NR_read
      return syscall(3, arg_1, arg_2, arg_3);
    case 225:  // __NR_readahead
      return syscall(225, arg_1, arg_3, arg_4, arg_5);
    case 85:  // __NR_readlink
      // follows symlinks
      return RunGuestSyscall___NR_readlink(arg_1, arg_2, arg_3);
    case 332:  // __NR_readlinkat
      // follows symlinks
      return RunGuestSyscall___NR_readlinkat(arg_1, arg_2, arg_3, arg_4);
    case 145:  // __NR_readv
      return syscall(145, arg_1, arg_2, arg_3);
    case 88:  // __NR_reboot
      return syscall(88, arg_1, arg_2, arg_3, arg_4);
    case 291:  // __NR_recv
      // socketcall
      return RunGuestSyscall___NR_recv(arg_1, arg_2, arg_3, arg_4);
    case 292:  // __NR_recvfrom
      // socketcall
      return RunGuestSyscall___NR_recvfrom(arg_1, arg_2, arg_3, arg_4, arg_5, arg_6);
    case 365:  // __NR_recvmmsg
      // socketcall
      return RunGuestSyscall___NR_recvmmsg(arg_1, arg_2, arg_3, arg_4, arg_5);
    case 417:  // __NR_recvmmsg_time64
      return syscall(417, arg_1, arg_2, arg_3, arg_4, arg_5);
    case 297:  // __NR_recvmsg
      // socketcall
      return RunGuestSyscall___NR_recvmsg(arg_1, arg_2, arg_3);
    case 253:  // __NR_remap_file_pages
      return syscall(257, arg_1, arg_2, arg_3, arg_4, arg_5);
    case 235:  // __NR_removexattr
      return syscall(235, arg_1, arg_2);
    case 38:  // __NR_rename
      return syscall(38, arg_1, arg_2);
    case 329:  // __NR_renameat
      return syscall(302, arg_1, arg_2, arg_3, arg_4);
    case 382:  // __NR_renameat2
      return syscall(353, arg_1, arg_2, arg_3, arg_4, arg_5);
    case 310:  // __NR_request_key
      return syscall(287, arg_1, arg_2, arg_3, arg_4);
    case 0:  // __NR_restart_syscall
      return syscall(0);
    case 40:  // __NR_rmdir
      return syscall(40, arg_1);
    case 398:  // __NR_rseq
      return syscall(386, arg_1, arg_2, arg_3, arg_4);
    case 174:  // __NR_rt_sigaction
      // changes signal action
      return RunGuestSyscall___NR_rt_sigaction(arg_1, arg_2, arg_3, arg_4);
    case 176:  // __NR_rt_sigpending
      return syscall(176, arg_1, arg_2);
    case 175:  // __NR_rt_sigprocmask
      return syscall(175, arg_1, arg_2, arg_3, arg_4);
    case 178:  // __NR_rt_sigqueueinfo
      return syscall(178, arg_1, arg_2, arg_3);
    case 173:  // __NR_rt_sigreturn
      // missing prototype
      TRACE("unsupported syscall __NR_rt_sigreturn");
      errno = ENOSYS;
      return -1;
    case 179:  // __NR_rt_sigsuspend
      return syscall(179, arg_1, arg_2);
    case 177:  // __NR_rt_sigtimedwait
      return syscall(177, arg_1, arg_2, arg_3, arg_4);
    case 421:  // __NR_rt_sigtimedwait_time64
      return syscall(421, arg_1, arg_2, arg_3, arg_4);
    case 363:  // __NR_rt_tgsigqueueinfo
      return syscall(335, arg_1, arg_2, arg_3, arg_4);
    case 159:  // __NR_sched_get_priority_max
      return syscall(159, arg_1);
    case 160:  // __NR_sched_get_priority_min
      return syscall(160, arg_1);
    case 242:  // __NR_sched_getaffinity
      return syscall(242, arg_1, arg_2, arg_3);
    case 381:  // __NR_sched_getattr
      return syscall(352, arg_1, arg_2, arg_3, arg_4);
    case 155:  // __NR_sched_getparam
      return syscall(155, arg_1, arg_2);
    case 157:  // __NR_sched_getscheduler
      return syscall(157, arg_1);
    case 161:  // __NR_sched_rr_get_interval
      return syscall(161, arg_1, arg_2);
    case 423:  // __NR_sched_rr_get_interval_time64
      return syscall(423, arg_1, arg_2);
    case 241:  // __NR_sched_setaffinity
      return syscall(241, arg_1, arg_2, arg_3);
    case 380:  // __NR_sched_setattr
      return syscall(351, arg_1, arg_2, arg_3);
    case 154:  // __NR_sched_setparam
      return syscall(154, arg_1, arg_2);
    case 156:  // __NR_sched_setscheduler
      return syscall(156, arg_1, arg_2, arg_3);
    case 158:  // __NR_sched_yield
      return syscall(158);
    case 383:  // __NR_seccomp
      return syscall(354, arg_1, arg_2, arg_3);
    case 300:  // __NR_semctl
      // sys_old_semctl on arm but sys_semctl on x86
      return RunGuestSyscall___NR_semctl(arg_1, arg_2, arg_3, arg_4);
    case 299:  // __NR_semget
      return syscall(393, arg_1, arg_2, arg_3);
    case 298:  // __NR_semop
      // missing on x86
      return RunGuestSyscall___NR_semop(arg_1, arg_2, arg_3);
    case 312:  // __NR_semtimedop
      // missing on x86
      return RunGuestSyscall___NR_semtimedop(arg_1, arg_2, arg_3, arg_4);
    case 420:  // __NR_semtimedop_time64
      return syscall(420, arg_1, arg_2, arg_3, arg_4);
    case 289:  // __NR_send
      // socketcall
      return RunGuestSyscall___NR_send(arg_1, arg_2, arg_3, arg_4);
    case 187:  // __NR_sendfile
      return syscall(187, arg_1, arg_2, arg_3, arg_4);
    case 239:  // __NR_sendfile64
      return syscall(239, arg_1, arg_2, arg_3, arg_4);
    case 374:  // __NR_sendmmsg
      // socketcall
      return RunGuestSyscall___NR_sendmmsg(arg_1, arg_2, arg_3, arg_4);
    case 296:  // __NR_sendmsg
      // socketcall
      return RunGuestSyscall___NR_sendmsg(arg_1, arg_2, arg_3);
    case 290:  // __NR_sendto
      // socketcall
      return RunGuestSyscall___NR_sendto(arg_1, arg_2, arg_3, arg_4, arg_5, arg_6);
    case 321:  // __NR_set_mempolicy
      // missing prototype
      TRACE("unsupported syscall __NR_set_mempolicy");
      errno = ENOSYS;
      return -1;
    case 338:  // __NR_set_robust_list
      return syscall(311, arg_1, arg_2);
    case 256:  // __NR_set_tid_address
      return syscall(258, arg_1);
    case 121:  // __NR_setdomainname
      return syscall(121, arg_1, arg_2);
    case 139:  // __NR_setfsgid
      return syscall(139, arg_1);
    case 216:  // __NR_setfsgid32
      return syscall(216, arg_1);
    case 138:  // __NR_setfsuid
      return syscall(138, arg_1);
    case 215:  // __NR_setfsuid32
      return syscall(215, arg_1);
    case 46:  // __NR_setgid
      return syscall(46, arg_1);
    case 214:  // __NR_setgid32
      return syscall(214, arg_1);
    case 81:  // __NR_setgroups
      return syscall(81, arg_1, arg_2);
    case 206:  // __NR_setgroups32
      return syscall(206, arg_1, arg_2);
    case 74:  // __NR_sethostname
      return syscall(74, arg_1, arg_2);
    case 104:  // __NR_setitimer
      return syscall(104, arg_1, arg_2, arg_3);
    case 375:  // __NR_setns
      return syscall(346, arg_1, arg_2);
    case 57:  // __NR_setpgid
      return syscall(57, arg_1, arg_2);
    case 97:  // __NR_setpriority
      return syscall(97, arg_1, arg_2, arg_3);
    case 71:  // __NR_setregid
      return syscall(71, arg_1, arg_2);
    case 204:  // __NR_setregid32
      return syscall(204, arg_1, arg_2);
    case 170:  // __NR_setresgid
      return syscall(170, arg_1, arg_2, arg_3);
    case 210:  // __NR_setresgid32
      return syscall(210, arg_1, arg_2, arg_3);
    case 164:  // __NR_setresuid
      return syscall(164, arg_1, arg_2, arg_3);
    case 208:  // __NR_setresuid32
      return syscall(208, arg_1, arg_2, arg_3);
    case 70:  // __NR_setreuid
      return syscall(70, arg_1, arg_2);
    case 203:  // __NR_setreuid32
      return syscall(203, arg_1, arg_2);
    case 75:  // __NR_setrlimit
      return syscall(75, arg_1, arg_2);
    case 66:  // __NR_setsid
      return syscall(66);
    case 294:  // __NR_setsockopt
      // socketcall
      return RunGuestSyscall___NR_setsockopt(arg_1, arg_2, arg_3, arg_4, arg_5);
    case 79:  // __NR_settimeofday
      return syscall(79, arg_1, arg_2);
    case 23:  // __NR_setuid
      return syscall(23, arg_1);
    case 213:  // __NR_setuid32
      return syscall(213, arg_1);
    case 226:  // __NR_setxattr
      return syscall(226, arg_1, arg_2, arg_3, arg_4, arg_5);
    case 305:  // __NR_shmat
      return syscall(397, arg_1, arg_2, arg_3);
    case 308:  // __NR_shmctl
      // sys_old_shmctl on arm but sys_shmctl on x86
      return RunGuestSyscall___NR_shmctl(arg_1, arg_2, arg_3);
    case 306:  // __NR_shmdt
      return syscall(398, arg_1);
    case 307:  // __NR_shmget
      return syscall(395, arg_1, arg_2, arg_3);
    case 293:  // __NR_shutdown
      // socketcall
      return RunGuestSyscall___NR_shutdown(arg_1, arg_2);
    case 67:  // __NR_sigaction
      // changes signal action
      return RunGuestSyscall___NR_sigaction(arg_1, arg_2, arg_3);
    case 186:  // __NR_sigaltstack
      // changes signal stack
      return RunGuestSyscall___NR_sigaltstack(arg_1, arg_2);
    case 349:  // __NR_signalfd
      return syscall(321, arg_1, arg_2, arg_3);
    case 355:  // __NR_signalfd4
      return syscall(327, arg_1, arg_2, arg_3, arg_4);
    case 73:  // __NR_sigpending
      return syscall(73, arg_1);
    case 126:  // __NR_sigprocmask
      return syscall(126, arg_1, arg_2, arg_3);
    case 119:  // __NR_sigreturn
      // missing prototype
      TRACE("unsupported syscall __NR_sigreturn");
      errno = ENOSYS;
      return -1;
    case 72:  // __NR_sigsuspend
      return syscall(72, arg_1, arg_2, arg_3);
    case 281:  // __NR_socket
      // socketcall
      return RunGuestSyscall___NR_socket(arg_1, arg_2, arg_3);
    case 288:  // __NR_socketpair
      // socketcall
      return RunGuestSyscall___NR_socketpair(arg_1, arg_2, arg_3, arg_4);
    case 340:  // __NR_splice
      return syscall(313, arg_1, arg_2, arg_3, arg_4, arg_5, arg_6);
    case 106:  // __NR_stat
      return syscall(106, arg_1, arg_2);
    case 195:  // __NR_stat64
      // incompatible prototype
      return RunGuestSyscall___NR_stat64(arg_1, arg_2);
    case 99:  // __NR_statfs
      return syscall(99, arg_1, arg_2);
    case 266:  // __NR_statfs64
      // statfs64 size mismatch
      return RunGuestSyscall___NR_statfs64(arg_1, arg_2, arg_3);
    case 397:  // __NR_statx
      // follows symlinks
      return RunGuestSyscall___NR_statx(arg_1, arg_2, arg_3, arg_4, arg_5);
    case 115:  // __NR_swapoff
      return syscall(115, arg_1);
    case 87:  // __NR_swapon
      return syscall(87, arg_1, arg_2);
    case 83:  // __NR_symlink
      return syscall(83, arg_1, arg_2);
    case 331:  // __NR_symlinkat
      return syscall(304, arg_1, arg_2, arg_3);
    case 36:  // __NR_sync
      return syscall(36);
    case 373:  // __NR_syncfs
      return syscall(344, arg_1);
    case 135:  // __NR_sysfs
      return syscall(135, arg_1, arg_2, arg_3);
    case 116:  // __NR_sysinfo
      return syscall(116, arg_1);
    case 103:  // __NR_syslog
      return syscall(103, arg_1, arg_2, arg_3);
    case 342:  // __NR_tee
      return syscall(315, arg_1, arg_2, arg_3, arg_4);
    case 268:  // __NR_tgkill
      return syscall(270, arg_1, arg_2, arg_3);
    case 257:  // __NR_timer_create
      // incompatible prototype
      return RunGuestSyscall___NR_timer_create(arg_1, arg_2, arg_3);
    case 261:  // __NR_timer_delete
      return syscall(263, arg_1);
    case 260:  // __NR_timer_getoverrun
      return syscall(262, arg_1);
    case 259:  // __NR_timer_gettime
      return syscall(261, arg_1, arg_2);
    case 408:  // __NR_timer_gettime64
      return syscall(408, arg_1, arg_2);
    case 258:  // __NR_timer_settime
      return syscall(260, arg_1, arg_2, arg_3, arg_4);
    case 409:  // __NR_timer_settime64
      return syscall(409, arg_1, arg_2, arg_3, arg_4);
    case 350:  // __NR_timerfd_create
      return syscall(322, arg_1, arg_2);
    case 354:  // __NR_timerfd_gettime
      return syscall(326, arg_1, arg_2);
    case 410:  // __NR_timerfd_gettime64
      return syscall(410, arg_1, arg_2);
    case 353:  // __NR_timerfd_settime
      return syscall(325, arg_1, arg_2, arg_3, arg_4);
    case 411:  // __NR_timerfd_settime64
      return syscall(411, arg_1, arg_2, arg_3, arg_4);
    case 43:  // __NR_times
      return syscall(43, arg_1);
    case 238:  // __NR_tkill
      return syscall(238, arg_1, arg_2);
    case 92:  // __NR_truncate
      return syscall(92, arg_1, arg_2);
    case 193:  // __NR_truncate64
      return syscall(193, arg_1, arg_3, arg_4);
    case 191:  // __NR_ugetrlimit
      return syscall(191, arg_1, arg_2);
    case 60:  // __NR_umask
      return syscall(60, arg_1);
    case 52:  // __NR_umount2
      return syscall(52, arg_1, arg_2);
    case 122:  // __NR_uname
      return syscall(122, arg_1);
    case 10:  // __NR_unlink
      return syscall(10, arg_1);
    case 328:  // __NR_unlinkat
      return syscall(301, arg_1, arg_2, arg_3);
    case 337:  // __NR_unshare
      return syscall(310, arg_1);
    case 86:  // __NR_uselib
      return syscall(86, arg_1);
    case 388:  // __NR_userfaultfd
      return syscall(374, arg_1);
    case 62:  // __NR_ustat
      return syscall(62, arg_1, arg_2);
    case 348:  // __NR_utimensat
      return syscall(320, arg_1, arg_2, arg_3, arg_4);
    case 412:  // __NR_utimensat_time64
      return syscall(412, arg_1, arg_2, arg_3, arg_4);
    case 269:  // __NR_utimes
      return syscall(271, arg_1, arg_2);
    case 190:  // __NR_vfork
      // custom syscall
      return RunGuestSyscall___NR_vfork();
    case 111:  // __NR_vhangup
      return syscall(111);
    case 343:  // __NR_vmsplice
      return syscall(316, arg_1, arg_2, arg_3, arg_4);
    case 313:  // __NR_vserver
      return syscall(273);
    case 114:  // __NR_wait4
      return syscall(114, arg_1, arg_2, arg_3, arg_4);
    case 280:  // __NR_waitid
      return syscall(284, arg_1, arg_2, arg_3, arg_4, arg_5);
    case 4:  // __NR_write
      return syscall(4, arg_1, arg_2, arg_3);
    case 146:  // __NR_writev
      return syscall(146, arg_1, arg_2, arg_3);
    default:
      return RunUnknownGuestSyscall(guest_nr, arg_1, arg_2, arg_3, arg_4, arg_5, arg_6);
  }
}
