
kMachineOpMacroFeGetExceptionsTranslateMemBaseDispReg,
    kMachineOpMacroFeSetExceptionsAndRoundImmTranslateMemBaseDispImm,
    kMachineOpMacroFeSetExceptionsAndRoundTranslateRegMemBaseDispRegReg,
    kMachineOpMacroFeSetExceptionsImmTranslateMemBaseDispImm,
    kMachineOpMacroFeSetExceptionsTranslateRegMemBaseDispReg,
    kMachineOpMacroFeSetRoundImmTranslateMemBaseDispMemBaseDispImm, kMachineOpMacroReverseBitsU64,
